//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gym.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string Name { get; set; }
        public int DNI { get; set; }
        public int Age { get; set; }
        public bool HasMedCertificate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> LastPaid { get; set; }
        public Nullable<System.Guid> RoutineId { get; set; }
        public byte[] Photo { get; set; }
    }
}
