//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gym.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IntegratekGYMEntities : DbContext
    {
        public IntegratekGYMEntities()
            : base("name=IntegratekGYMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Exercise> Exercise { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Routine> Routine { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<TargetArea> TargetArea { get; set; }
        public virtual DbSet<ExLog> ExLog { get; set; }
    }
}
