//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gym.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExLog
    {
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string Module { get; set; }
        public string Action { get; set; }
        public string ExMessage { get; set; }
        public string ExStackTrace { get; set; }
        public string ExSource { get; set; }
        public Nullable<bool> InnerException { get; set; }
        public string InnerMessage { get; set; }
        public string InnerStackTrace { get; set; }
        public string InnerSource { get; set; }
        public System.Guid id { get; set; }
    }
}
