//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gym.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routine
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ClientId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> TargetAreaId { get; set; }
        public int Exercises { get; set; }
        public string SetsRepsCSV { get; set; }
    }
}
