//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gym.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public Nullable<System.Guid> ClientId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
    }
}
